/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface IcmContext {
  'stacks' : Array<number>,
  'heroIndex' : [] | [bigint],
  'stage' : [] | [string],
  'playersRemaining' : bigint,
  'payoutType' : [] | [string],
  'payouts' : Array<number>,
}
export interface SessionData {
  'completedAt' : Time,
  'mistakeCount' : bigint,
  'mode' : [] | [string],
  'handsPlayed' : bigint,
  'spotResults' : Array<[string, string]>,
  'icmContext' : [] | [IcmContext],
  'scenario' : string,
  'correctCount' : bigint,
  'acceptableCount' : bigint,
  'stackRange' : string,
}
export interface SessionSummary {
  'completedAt' : Time,
  'mistakeCount' : bigint,
  'mode' : [] | [string],
  'handsPlayed' : bigint,
  'scenario' : string,
  'correctCount' : bigint,
  'acceptableCount' : bigint,
  'stackRange' : string,
}
export interface SpotStat { 'attempts' : bigint, 'mistakes' : bigint }
export type Time = bigint;
export interface UserProfile {
  'principal' : Principal,
  'mistakeCount' : bigint,
  'totalHands' : bigint,
  'isPremium' : boolean,
  'spotStats' : Array<[string, SpotStat]>,
  'createdAt' : Time,
  'sessions' : Array<SessionSummary>,
  'correctCount' : bigint,
  'acceptableCount' : bigint,
  'totalSessions' : bigint,
}
export interface _SERVICE {
  'ensureProfile' : ActorMethod<[], undefined>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'saveSession' : ActorMethod<[SessionData], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];