/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SpotStat = IDL.Record({
  'attempts' : IDL.Nat,
  'mistakes' : IDL.Nat,
});
export const Time = IDL.Int;
export const SessionSummary = IDL.Record({
  'completedAt' : Time,
  'mistakeCount' : IDL.Nat,
  'mode' : IDL.Opt(IDL.Text),
  'handsPlayed' : IDL.Nat,
  'scenario' : IDL.Text,
  'correctCount' : IDL.Nat,
  'acceptableCount' : IDL.Nat,
  'stackRange' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'mistakeCount' : IDL.Nat,
  'totalHands' : IDL.Nat,
  'isPremium' : IDL.Bool,
  'spotStats' : IDL.Vec(IDL.Tuple(IDL.Text, SpotStat)),
  'createdAt' : Time,
  'sessions' : IDL.Vec(SessionSummary),
  'correctCount' : IDL.Nat,
  'acceptableCount' : IDL.Nat,
  'totalSessions' : IDL.Nat,
});
export const IcmContext = IDL.Record({
  'stacks' : IDL.Vec(IDL.Float64),
  'heroIndex' : IDL.Opt(IDL.Nat),
  'stage' : IDL.Opt(IDL.Text),
  'playersRemaining' : IDL.Nat,
  'payoutType' : IDL.Opt(IDL.Text),
  'payouts' : IDL.Vec(IDL.Float64),
});
export const SessionData = IDL.Record({
  'completedAt' : Time,
  'mistakeCount' : IDL.Nat,
  'mode' : IDL.Opt(IDL.Text),
  'handsPlayed' : IDL.Nat,
  'spotResults' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'icmContext' : IDL.Opt(IcmContext),
  'scenario' : IDL.Text,
  'correctCount' : IDL.Nat,
  'acceptableCount' : IDL.Nat,
  'stackRange' : IDL.Text,
});

export const idlService = IDL.Service({
  'ensureProfile' : IDL.Func([], [], []),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'saveSession' : IDL.Func([SessionData], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SpotStat = IDL.Record({ 'attempts' : IDL.Nat, 'mistakes' : IDL.Nat });
  const Time = IDL.Int;
  const SessionSummary = IDL.Record({
    'completedAt' : Time,
    'mistakeCount' : IDL.Nat,
    'mode' : IDL.Opt(IDL.Text),
    'handsPlayed' : IDL.Nat,
    'scenario' : IDL.Text,
    'correctCount' : IDL.Nat,
    'acceptableCount' : IDL.Nat,
    'stackRange' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'mistakeCount' : IDL.Nat,
    'totalHands' : IDL.Nat,
    'isPremium' : IDL.Bool,
    'spotStats' : IDL.Vec(IDL.Tuple(IDL.Text, SpotStat)),
    'createdAt' : Time,
    'sessions' : IDL.Vec(SessionSummary),
    'correctCount' : IDL.Nat,
    'acceptableCount' : IDL.Nat,
    'totalSessions' : IDL.Nat,
  });
  const IcmContext = IDL.Record({
    'stacks' : IDL.Vec(IDL.Float64),
    'heroIndex' : IDL.Opt(IDL.Nat),
    'stage' : IDL.Opt(IDL.Text),
    'playersRemaining' : IDL.Nat,
    'payoutType' : IDL.Opt(IDL.Text),
    'payouts' : IDL.Vec(IDL.Float64),
  });
  const SessionData = IDL.Record({
    'completedAt' : Time,
    'mistakeCount' : IDL.Nat,
    'mode' : IDL.Opt(IDL.Text),
    'handsPlayed' : IDL.Nat,
    'spotResults' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'icmContext' : IDL.Opt(IcmContext),
    'scenario' : IDL.Text,
    'correctCount' : IDL.Nat,
    'acceptableCount' : IDL.Nat,
    'stackRange' : IDL.Text,
  });
  
  return IDL.Service({
    'ensureProfile' : IDL.Func([], [], []),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'saveSession' : IDL.Func([SessionData], [], []),
  });
};

export const init = ({ IDL }) => { return []; };