/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface IcmContext {
    stacks: Array<number>;
    heroIndex?: bigint;
    stage?: string;
    playersRemaining: bigint;
    payoutType?: string;
    payouts: Array<number>;
}
export interface SpotStat {
    attempts: bigint;
    mistakes: bigint;
}
export type Time = bigint;
export interface SessionSummary {
    completedAt: Time;
    mistakeCount: bigint;
    mode?: string;
    handsPlayed: bigint;
    scenario: string;
    correctCount: bigint;
    acceptableCount: bigint;
    stackRange: string;
}
export interface UserProfile {
    principal: Principal;
    mistakeCount: bigint;
    totalHands: bigint;
    isPremium: boolean;
    spotStats: Array<[string, SpotStat]>;
    createdAt: Time;
    sessions: Array<SessionSummary>;
    correctCount: bigint;
    acceptableCount: bigint;
    totalSessions: bigint;
}
export interface SessionData {
    completedAt: Time;
    mistakeCount: bigint;
    mode?: string;
    handsPlayed: bigint;
    spotResults: Array<[string, string]>;
    icmContext?: IcmContext;
    scenario: string;
    correctCount: bigint;
    acceptableCount: bigint;
    stackRange: string;
}
export interface backendInterface {
    ensureProfile(): Promise<void>;
    getProfile(): Promise<UserProfile | null>;
    saveSession(data: SessionData): Promise<void>;
}
import type { IcmContext as _IcmContext, SessionData as _SessionData, SessionSummary as _SessionSummary, SpotStat as _SpotStat, Time as _Time, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async ensureProfile(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.ensureProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ensureProfile();
            return result;
        }
    }
    async getProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveSession(arg0: SessionData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSession(to_candid_SessionData_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSession(to_candid_SessionData_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_SessionSummary_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionSummary): SessionSummary {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    mistakeCount: bigint;
    totalHands: bigint;
    isPremium: boolean;
    spotStats: Array<[string, _SpotStat]>;
    createdAt: _Time;
    sessions: Array<_SessionSummary>;
    correctCount: bigint;
    acceptableCount: bigint;
    totalSessions: bigint;
}): {
    principal: Principal;
    mistakeCount: bigint;
    totalHands: bigint;
    isPremium: boolean;
    spotStats: Array<[string, SpotStat]>;
    createdAt: Time;
    sessions: Array<SessionSummary>;
    correctCount: bigint;
    acceptableCount: bigint;
    totalSessions: bigint;
} {
    return {
        principal: value.principal,
        mistakeCount: value.mistakeCount,
        totalHands: value.totalHands,
        isPremium: value.isPremium,
        spotStats: value.spotStats,
        createdAt: value.createdAt,
        sessions: from_candid_vec_n4(_uploadFile, _downloadFile, value.sessions),
        correctCount: value.correctCount,
        acceptableCount: value.acceptableCount,
        totalSessions: value.totalSessions
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedAt: _Time;
    mistakeCount: bigint;
    mode: [] | [string];
    handsPlayed: bigint;
    scenario: string;
    correctCount: bigint;
    acceptableCount: bigint;
    stackRange: string;
}): {
    completedAt: Time;
    mistakeCount: bigint;
    mode?: string;
    handsPlayed: bigint;
    scenario: string;
    correctCount: bigint;
    acceptableCount: bigint;
    stackRange: string;
} {
    return {
        completedAt: value.completedAt,
        mistakeCount: value.mistakeCount,
        mode: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.mode)),
        handsPlayed: value.handsPlayed,
        scenario: value.scenario,
        correctCount: value.correctCount,
        acceptableCount: value.acceptableCount,
        stackRange: value.stackRange
    };
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SessionSummary>): Array<SessionSummary> {
    return value.map((x)=>from_candid_SessionSummary_n5(_uploadFile, _downloadFile, x));
}
function to_candid_IcmContext_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IcmContext): _IcmContext {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_SessionData_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionData): _SessionData {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stacks: Array<number>;
    heroIndex?: bigint;
    stage?: string;
    playersRemaining: bigint;
    payoutType?: string;
    payouts: Array<number>;
}): {
    stacks: Array<number>;
    heroIndex: [] | [bigint];
    stage: [] | [string];
    playersRemaining: bigint;
    payoutType: [] | [string];
    payouts: Array<number>;
} {
    return {
        stacks: value.stacks,
        heroIndex: value.heroIndex ? candid_some(value.heroIndex) : candid_none(),
        stage: value.stage ? candid_some(value.stage) : candid_none(),
        playersRemaining: value.playersRemaining,
        payoutType: value.payoutType ? candid_some(value.payoutType) : candid_none(),
        payouts: value.payouts
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completedAt: Time;
    mistakeCount: bigint;
    mode?: string;
    handsPlayed: bigint;
    spotResults: Array<[string, string]>;
    icmContext?: IcmContext;
    scenario: string;
    correctCount: bigint;
    acceptableCount: bigint;
    stackRange: string;
}): {
    completedAt: _Time;
    mistakeCount: bigint;
    mode: [] | [string];
    handsPlayed: bigint;
    spotResults: Array<[string, string]>;
    icmContext: [] | [_IcmContext];
    scenario: string;
    correctCount: bigint;
    acceptableCount: bigint;
    stackRange: string;
} {
    return {
        completedAt: value.completedAt,
        mistakeCount: value.mistakeCount,
        mode: value.mode ? candid_some(value.mode) : candid_none(),
        handsPlayed: value.handsPlayed,
        spotResults: value.spotResults,
        icmContext: value.icmContext ? candid_some(to_candid_IcmContext_n10(_uploadFile, _downloadFile, value.icmContext)) : candid_none(),
        scenario: value.scenario,
        correctCount: value.correctCount,
        acceptableCount: value.acceptableCount,
        stackRange: value.stackRange
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
